export const SET_NOTES_DO = "SET_NOTES_DO";
export const SET_NOTES_DONE = "SET_NOTES_DONE";
export const SET_NOTES_ERROR = "SET_NOTES_ERROR"
export const SET_NOTES_LOADING = "SET_NOTES_LOADING";
export const SAVE_NOTE_DO_LIST = "SAVE_NOTE_DO_LIST";
export const CREATE_NOTE_DO_LIST = "CREATE_NOTE_DO_LIST"
export const DELETE_NOTE = "DELETE_NOTE"

export const SET_REG_REDIRECT = "SET_REG_REDIRECT";
export const SET_REG_ERROR = "SET_REG_ERROR";
export const SET_REG_LOADING = "SET_REG_LOADING";

export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const SET_LOGGED_ERROR = "SET_LOGGED_ERROR"
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_AUTH_TOKEN = "SET_TOKEN";