export const SET_NOTES = "SET_NOTES";
export const SET_NOTES_LOADING = "SET_NOTES_LOADING";

export const REG_SET_STATUS = "REG_SET_STATUS";
export const REG_SET_DETAIL = "REG_SET_DETAIL";
export const REG_SET_LOADING = "REG_SET_LOADING";

export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const SET_ISLOGGED = "SET_ISLOGGED";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_TOKEN = "SET_TOKEN";